-- ============================================================================
-- ZMC Alarm Exporter - 数据库初始化脚本
-- 版本: 1.0.0
-- 描述: 创建告警同步所需的辅助表、配置表和日志表
-- 数据库: Oracle
-- ============================================================================

-- ============================================================================
-- 1. 配置表 (NM_ALARM_SYNC_CONFIG)
-- 用途: 存储所有同步服务的配置参数，支持加密存储敏感信息
-- ============================================================================
CREATE TABLE NM_ALARM_SYNC_CONFIG (
    CONFIG_ID         NUMBER(12)      NOT NULL,    -- 配置记录唯一标识
    CONFIG_GROUP      VARCHAR2(50)    NOT NULL,    -- 配置分组名称，用于逻辑分类配置项
    CONFIG_KEY        VARCHAR2(100)   NOT NULL,    -- 配置键名，在分组内唯一
    CONFIG_VALUE      VARCHAR2(500),               -- 配置值（非敏感信息）
    CONFIG_VALUE_ENC  VARCHAR2(1000),              -- 加密配置值（用于存储密码等敏感信息）
    IS_ENCRYPTED      CHAR(1)         DEFAULT 'N', -- 是否为加密配置: Y-是, N-否
    CONFIG_DESC       VARCHAR2(500),               -- 配置项描述说明
    IS_REQUIRED       CHAR(1)         DEFAULT 'Y', -- 是否必填: Y-是, N-否
    DEFAULT_VALUE     VARCHAR2(500),               -- 默认值，当CONFIG_VALUE为空时使用
    UPDATE_TIME       TIMESTAMP       DEFAULT SYSTIMESTAMP, -- 最后更新时间
    UPDATE_BY         VARCHAR2(50),                -- 最后更新人
    CONSTRAINT PK_ALARM_SYNC_CONFIG PRIMARY KEY (CONFIG_ID),
    CONSTRAINT UK_SYNC_CONFIG UNIQUE (CONFIG_GROUP, CONFIG_KEY)
);

-- 配置表字段注释
COMMENT ON TABLE NM_ALARM_SYNC_CONFIG IS '告警同步服务配置表，存储数据库连接、Alertmanager连接、同步参数等所有配置信息';
COMMENT ON COLUMN NM_ALARM_SYNC_CONFIG.CONFIG_ID IS '配置记录唯一标识，由序列SEQ_ALARM_SYNC_CONFIG生成';
COMMENT ON COLUMN NM_ALARM_SYNC_CONFIG.CONFIG_GROUP IS '配置分组名称，如: ZMC_ORACLE-Oracle数据库配置, ALERTMANAGER-Alertmanager配置, SYNC_SERVICE-同步服务配置';
COMMENT ON COLUMN NM_ALARM_SYNC_CONFIG.CONFIG_KEY IS '配置键名，在同一分组内唯一，如: DB_HOST, DB_PORT, SCAN_INTERVAL等';
COMMENT ON COLUMN NM_ALARM_SYNC_CONFIG.CONFIG_VALUE IS '配置值，存储非敏感的配置信息';
COMMENT ON COLUMN NM_ALARM_SYNC_CONFIG.CONFIG_VALUE_ENC IS '加密配置值，用于存储密码、API Key等敏感信息，使用AES256加密';
COMMENT ON COLUMN NM_ALARM_SYNC_CONFIG.IS_ENCRYPTED IS '标识该配置是否为加密配置: Y-加密配置(读取CONFIG_VALUE_ENC), N-普通配置(读取CONFIG_VALUE)';
COMMENT ON COLUMN NM_ALARM_SYNC_CONFIG.CONFIG_DESC IS '配置项的详细描述，说明该配置的用途和有效值范围';
COMMENT ON COLUMN NM_ALARM_SYNC_CONFIG.IS_REQUIRED IS '标识该配置是否为必填项: Y-必填, N-可选';
COMMENT ON COLUMN NM_ALARM_SYNC_CONFIG.DEFAULT_VALUE IS '配置默认值，当CONFIG_VALUE为空时使用此值';
COMMENT ON COLUMN NM_ALARM_SYNC_CONFIG.UPDATE_TIME IS '配置最后修改时间，用于跟踪配置变更';
COMMENT ON COLUMN NM_ALARM_SYNC_CONFIG.UPDATE_BY IS '最后修改该配置的用户或系统标识';

-- 配置表序列
CREATE SEQUENCE SEQ_ALARM_SYNC_CONFIG START WITH 1 INCREMENT BY 1 NOCACHE;


-- ============================================================================
-- 2. 同步状态跟踪表 (NM_ALARM_SYNC_STATUS)
-- 用途: 跟踪每条告警的同步状态，记录推送历史和错误信息
-- ============================================================================
CREATE TABLE NM_ALARM_SYNC_STATUS (
    SYNC_ID           NUMBER(12)      NOT NULL,    -- 同步记录唯一标识
    EVENT_INST_ID     NUMBER(13)      NOT NULL,    -- 关联的告警事件ID (NM_ALARM_EVENT.EVENT_INST_ID)
    ALARM_INST_ID     NUMBER(13),                  -- 关联的告警汇总ID (NM_ALARM_CDR.ALARM_INST_ID)
    SYNC_STATUS       VARCHAR2(20)    NOT NULL,    -- 当前同步状态: PENDING/FIRING/RESOLVED/SILENCED/ERROR
    ZMC_ALARM_STATE   VARCHAR2(10),                -- ZMC侧告警状态: U-未确认/A-自动恢复/M-手工清除/C-已确认
    LAST_PUSH_TIME    TIMESTAMP,                   -- 最后一次推送到Alertmanager的时间
    PUSH_COUNT        NUMBER(9)       DEFAULT 0,   -- 累计推送次数（包括心跳保活）
    AM_FINGERPRINT    VARCHAR2(100),               -- Alertmanager返回的告警指纹ID，用于后续更新
    SILENCE_ID        VARCHAR2(100),               -- 如果告警被静默，记录Alertmanager返回的Silence ID
    ERROR_COUNT       NUMBER(9)       DEFAULT 0,   -- 累计错误次数，用于错误重试策略
    LAST_ERROR        VARCHAR2(2000),              -- 最后一次错误信息
    CREATE_TIME       TIMESTAMP       DEFAULT SYSTIMESTAMP, -- 同步记录创建时间
    UPDATE_TIME       TIMESTAMP       DEFAULT SYSTIMESTAMP, -- 最后更新时间
    CONSTRAINT PK_ALARM_SYNC_STATUS PRIMARY KEY (SYNC_ID),
    CONSTRAINT UK_SYNC_EVENT_INST UNIQUE (EVENT_INST_ID)
);

-- 同步状态表字段注释
COMMENT ON TABLE NM_ALARM_SYNC_STATUS IS '告警同步状态跟踪表，记录每条ZMC告警与Prometheus/Alertmanager同步的状态';
COMMENT ON COLUMN NM_ALARM_SYNC_STATUS.SYNC_ID IS '同步记录唯一标识，由序列SEQ_ALARM_SYNC_STATUS生成';
COMMENT ON COLUMN NM_ALARM_SYNC_STATUS.EVENT_INST_ID IS '关联NM_ALARM_EVENT表的告警事件ID，一对一关系';
COMMENT ON COLUMN NM_ALARM_SYNC_STATUS.ALARM_INST_ID IS '关联NM_ALARM_CDR表的告警汇总ID，用于获取告警确认/清除状态';
COMMENT ON COLUMN NM_ALARM_SYNC_STATUS.SYNC_STATUS IS '当前同步状态: PENDING-待同步, FIRING-告警中, RESOLVED-已恢复, SILENCED-已静默, ERROR-同步错误';
COMMENT ON COLUMN NM_ALARM_SYNC_STATUS.ZMC_ALARM_STATE IS 'ZMC系统中的告警状态: U-未确认(默认), A-自动恢复, M-手工清除, C-已确认';
COMMENT ON COLUMN NM_ALARM_SYNC_STATUS.LAST_PUSH_TIME IS '最后一次成功推送到Alertmanager的时间，用于心跳保活判断';
COMMENT ON COLUMN NM_ALARM_SYNC_STATUS.PUSH_COUNT IS '累计推送次数，包括首次推送和心跳保活推送';
COMMENT ON COLUMN NM_ALARM_SYNC_STATUS.AM_FINGERPRINT IS 'Alertmanager为该告警生成的唯一指纹，格式为MD5哈希值';
COMMENT ON COLUMN NM_ALARM_SYNC_STATUS.SILENCE_ID IS '当告警被静默时，Alertmanager返回的Silence规则ID，用于后续删除静默';
COMMENT ON COLUMN NM_ALARM_SYNC_STATUS.ERROR_COUNT IS '连续错误次数，成功推送后重置为0，用于实现指数退避重试';
COMMENT ON COLUMN NM_ALARM_SYNC_STATUS.LAST_ERROR IS '最后一次同步错误的详细信息，包括HTTP状态码和响应内容';
COMMENT ON COLUMN NM_ALARM_SYNC_STATUS.CREATE_TIME IS '该同步记录的创建时间';
COMMENT ON COLUMN NM_ALARM_SYNC_STATUS.UPDATE_TIME IS '该同步记录的最后更新时间';

-- 同步状态表序列
CREATE SEQUENCE SEQ_ALARM_SYNC_STATUS START WITH 1 INCREMENT BY 1 NOCACHE;

-- 同步状态表索引
CREATE INDEX IDX_SYNC_STATUS_STATUS ON NM_ALARM_SYNC_STATUS(SYNC_STATUS);
CREATE INDEX IDX_SYNC_STATUS_PUSH_TIME ON NM_ALARM_SYNC_STATUS(LAST_PUSH_TIME);
CREATE INDEX IDX_SYNC_STATUS_ZMC_STATE ON NM_ALARM_SYNC_STATUS(ZMC_ALARM_STATE);
CREATE INDEX IDX_SYNC_STATUS_CREATE ON NM_ALARM_SYNC_STATUS(CREATE_TIME);


-- ============================================================================
-- 3. 同步日志表 (NM_ALARM_SYNC_LOG)
-- 用途: 记录所有同步操作的详细日志，用于审计和问题排查
-- ============================================================================
CREATE TABLE NM_ALARM_SYNC_LOG (
    LOG_ID            NUMBER(12)      NOT NULL,    -- 日志记录唯一标识
    SYNC_BATCH_ID     VARCHAR2(50),                -- 同步批次ID，同一批次的操作共享此ID
    EVENT_INST_ID     NUMBER(13),                  -- 关联的告警事件ID
    OPERATION         VARCHAR2(30)    NOT NULL,    -- 操作类型
    OLD_STATUS        VARCHAR2(20),                -- 操作前的状态
    NEW_STATUS        VARCHAR2(20),                -- 操作后的状态
    REQUEST_URL       VARCHAR2(500),               -- 请求的API URL
    REQUEST_METHOD    VARCHAR2(10),                -- HTTP请求方法: GET/POST/DELETE
    REQUEST_PAYLOAD   CLOB,                        -- 请求体内容(JSON格式)
    RESPONSE_CODE     NUMBER(5),                   -- HTTP响应状态码
    RESPONSE_BODY     CLOB,                        -- 响应体内容
    ERROR_MESSAGE     VARCHAR2(2000),              -- 错误信息
    DURATION_MS       NUMBER(9),                   -- 操作耗时(毫秒)
    CREATE_TIME       TIMESTAMP       DEFAULT SYSTIMESTAMP, -- 日志记录时间
    CONSTRAINT PK_ALARM_SYNC_LOG PRIMARY KEY (LOG_ID)
);

-- 同步日志表字段注释
COMMENT ON TABLE NM_ALARM_SYNC_LOG IS '告警同步操作日志表，记录所有同步操作的详细信息，用于审计跟踪和问题排查';
COMMENT ON COLUMN NM_ALARM_SYNC_LOG.LOG_ID IS '日志记录唯一标识，由序列SEQ_ALARM_SYNC_LOG生成';
COMMENT ON COLUMN NM_ALARM_SYNC_LOG.SYNC_BATCH_ID IS '同步批次ID，格式为YYYYMMDDHHMMSS_UUID，同一次调度的所有操作共享此ID';
COMMENT ON COLUMN NM_ALARM_SYNC_LOG.EVENT_INST_ID IS '关联的告警事件ID，可为空(如配置加载等非告警操作)';
COMMENT ON COLUMN NM_ALARM_SYNC_LOG.OPERATION IS '操作类型: EXTRACT-抽取告警, PUSH_FIRING-推送活跃告警, PUSH_RESOLVED-推送恢复, CREATE_SILENCE-创建静默, DELETE_SILENCE-删除静默, HEARTBEAT-心跳保活, STATUS_CHECK-状态检查, CONFIG_LOAD-加载配置, ERROR-错误记录';
COMMENT ON COLUMN NM_ALARM_SYNC_LOG.OLD_STATUS IS '操作前的同步状态';
COMMENT ON COLUMN NM_ALARM_SYNC_LOG.NEW_STATUS IS '操作后的同步状态';
COMMENT ON COLUMN NM_ALARM_SYNC_LOG.REQUEST_URL IS '调用的Alertmanager API完整URL';
COMMENT ON COLUMN NM_ALARM_SYNC_LOG.REQUEST_METHOD IS 'HTTP请求方法: GET-查询, POST-创建/更新, DELETE-删除';
COMMENT ON COLUMN NM_ALARM_SYNC_LOG.REQUEST_PAYLOAD IS '发送的HTTP请求体，JSON格式，包含告警数据或静默规则';
COMMENT ON COLUMN NM_ALARM_SYNC_LOG.RESPONSE_CODE IS 'HTTP响应状态码: 200-成功, 4xx-客户端错误, 5xx-服务端错误';
COMMENT ON COLUMN NM_ALARM_SYNC_LOG.RESPONSE_BODY IS 'HTTP响应体内容，JSON格式';
COMMENT ON COLUMN NM_ALARM_SYNC_LOG.ERROR_MESSAGE IS '错误详细信息，包括异常类型和堆栈信息摘要';
COMMENT ON COLUMN NM_ALARM_SYNC_LOG.DURATION_MS IS '操作总耗时，单位毫秒，用于性能监控';
COMMENT ON COLUMN NM_ALARM_SYNC_LOG.CREATE_TIME IS '日志记录创建时间';

-- 同步日志表序列
CREATE SEQUENCE SEQ_ALARM_SYNC_LOG START WITH 1 INCREMENT BY 1 NOCACHE;

-- 同步日志表索引
CREATE INDEX IDX_SYNC_LOG_TIME ON NM_ALARM_SYNC_LOG(CREATE_TIME);
CREATE INDEX IDX_SYNC_LOG_EVENT ON NM_ALARM_SYNC_LOG(EVENT_INST_ID);
CREATE INDEX IDX_SYNC_LOG_BATCH ON NM_ALARM_SYNC_LOG(SYNC_BATCH_ID);
CREATE INDEX IDX_SYNC_LOG_OP ON NM_ALARM_SYNC_LOG(OPERATION);


-- ============================================================================
-- 4. 告警标签映射表 (NM_ALARM_LABEL_MAPPING)
-- 用途: 定义ZMC字段到Prometheus标签的映射规则
-- ============================================================================
CREATE TABLE NM_ALARM_LABEL_MAPPING (
    MAPPING_ID        NUMBER(12)      NOT NULL,    -- 映射记录唯一标识
    SOURCE_FIELD      VARCHAR2(100)   NOT NULL,    -- ZMC源字段名
    TARGET_LABEL      VARCHAR2(100)   NOT NULL,    -- Prometheus目标标签名
    TRANSFORM_TYPE    VARCHAR2(30)    DEFAULT 'DIRECT', -- 转换类型
    TRANSFORM_EXPR    VARCHAR2(1000),              -- 转换表达式(当TRANSFORM_TYPE不为DIRECT时)
    IS_ENABLED        CHAR(1)         DEFAULT 'Y', -- 是否启用: Y-启用, N-禁用
    LABEL_TYPE        VARCHAR2(20)    DEFAULT 'LABEL', -- 标签类型: LABEL-标签, ANNOTATION-注解
    SORT_ORDER        NUMBER(5)       DEFAULT 0,   -- 排序顺序
    CREATE_TIME       TIMESTAMP       DEFAULT SYSTIMESTAMP, -- 创建时间
    UPDATE_TIME       TIMESTAMP       DEFAULT SYSTIMESTAMP, -- 更新时间
    CONSTRAINT PK_ALARM_LABEL_MAPPING PRIMARY KEY (MAPPING_ID),
    CONSTRAINT UK_LABEL_MAPPING UNIQUE (SOURCE_FIELD, TARGET_LABEL)
);

-- 标签映射表字段注释
COMMENT ON TABLE NM_ALARM_LABEL_MAPPING IS '告警标签映射配置表，定义ZMC告警字段到Prometheus标签/注解的映射规则';
COMMENT ON COLUMN NM_ALARM_LABEL_MAPPING.MAPPING_ID IS '映射记录唯一标识，由序列生成';
COMMENT ON COLUMN NM_ALARM_LABEL_MAPPING.SOURCE_FIELD IS 'ZMC源字段名，支持: EVENT_INST_ID, ALARM_CODE, HOST_NAME, HOST_IP, BUSINESS_DOMAIN等';
COMMENT ON COLUMN NM_ALARM_LABEL_MAPPING.TARGET_LABEL IS 'Prometheus目标标签名，如: alertname, instance, severity, job等';
COMMENT ON COLUMN NM_ALARM_LABEL_MAPPING.TRANSFORM_TYPE IS '转换类型: DIRECT-直接映射, LOOKUP-查表映射, TEMPLATE-模板转换, SCRIPT-脚本转换';
COMMENT ON COLUMN NM_ALARM_LABEL_MAPPING.TRANSFORM_EXPR IS '转换表达式，如查表SQL、模板字符串或Python表达式';
COMMENT ON COLUMN NM_ALARM_LABEL_MAPPING.IS_ENABLED IS '是否启用该映射规则: Y-启用, N-禁用';
COMMENT ON COLUMN NM_ALARM_LABEL_MAPPING.LABEL_TYPE IS '标签类型: LABEL-Prometheus标签(用于匹配), ANNOTATION-注解(用于展示)';
COMMENT ON COLUMN NM_ALARM_LABEL_MAPPING.SORT_ORDER IS '标签输出顺序，数值越小越靠前';
COMMENT ON COLUMN NM_ALARM_LABEL_MAPPING.CREATE_TIME IS '映射规则创建时间';
COMMENT ON COLUMN NM_ALARM_LABEL_MAPPING.UPDATE_TIME IS '映射规则最后更新时间';

-- 标签映射表序列
CREATE SEQUENCE SEQ_ALARM_LABEL_MAPPING START WITH 1 INCREMENT BY 1 NOCACHE;


-- ============================================================================
-- 5. 初始化配置数据
-- ============================================================================

-- 5.1 ZMC Oracle 数据库连接配置
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'ZMC_ORACLE', 'DB_HOST', '10.101.1.42', 'N', 'ZMC Oracle数据库主机地址', 'Y', 'localhost', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'ZMC_ORACLE', 'DB_PORT', '1522', 'N', 'Oracle数据库监听端口', 'Y', '1521', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'ZMC_ORACLE', 'DB_SERVICE_NAME', 'rb', 'N', 'Oracle服务名(SERVICE_NAME)', 'Y', 'ORCL', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'ZMC_ORACLE', 'DB_USERNAME', 'zmc', 'N', 'Oracle数据库用户名', 'Y', NULL, 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'ZMC_ORACLE', 'DB_PASSWORD', 'smart', 'N', 'Oracle数据库密码(生产环境建议加密)', 'Y', NULL, 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'ZMC_ORACLE', 'DB_POOL_MIN', '2', 'N', '数据库连接池最小连接数', 'N', '2', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'ZMC_ORACLE', 'DB_POOL_MAX', '10', 'N', '数据库连接池最大连接数', 'N', '10', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'ZMC_ORACLE', 'DB_TIMEOUT', '30', 'N', '数据库连接超时时间(秒)', 'N', '30', 'SYSTEM');

-- 5.2 Alertmanager 连接配置
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'ALERTMANAGER', 'AM_URL', 'http://localhost:9093', 'N', 'Alertmanager API基础地址', 'Y', 'http://localhost:9093', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'ALERTMANAGER', 'AM_API_VERSION', 'v2', 'N', 'Alertmanager API版本', 'N', 'v2', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'ALERTMANAGER', 'AM_AUTH_ENABLED', 'false', 'N', '是否启用Alertmanager认证', 'N', 'false', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'ALERTMANAGER', 'AM_USERNAME', NULL, 'N', 'Alertmanager Basic Auth用户名', 'N', NULL, 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'ALERTMANAGER', 'AM_PASSWORD', NULL, 'Y', 'Alertmanager Basic Auth密码(加密存储)', 'N', NULL, 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'ALERTMANAGER', 'AM_TIMEOUT', '30', 'N', 'Alertmanager API请求超时(秒)', 'N', '30', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'ALERTMANAGER', 'AM_RETRY_COUNT', '3', 'N', 'API调用失败重试次数', 'N', '3', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'ALERTMANAGER', 'AM_RETRY_INTERVAL', '1000', 'N', '重试间隔时间(毫秒)', 'N', '1000', 'SYSTEM');

-- 5.3 OpsGenie 直连配置（备选方案）
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'OPSGENIE', 'OG_DIRECT_ENABLED', 'false', 'N', '是否启用OpsGenie直连模式(绕过Alertmanager)', 'N', 'false', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'OPSGENIE', 'OG_API_URL', 'https://api.opsgenie.com', 'N', 'OpsGenie API地址(US区域)', 'N', 'https://api.opsgenie.com', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'OPSGENIE', 'OG_API_KEY', NULL, 'Y', 'OpsGenie API Key(加密存储)', 'N', NULL, 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'OPSGENIE', 'OG_DEFAULT_TEAM', NULL, 'N', 'OpsGenie默认告警接收团队', 'N', NULL, 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'OPSGENIE', 'OG_REGION', 'US', 'N', 'OpsGenie服务区域: US-美国, EU-欧洲', 'N', 'US', 'SYSTEM');

-- 5.4 同步服务配置
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SYNC_SERVICE', 'ENABLE_SYNC', 'true', 'N', '是否启用告警同步服务', 'Y', 'true', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SYNC_SERVICE', 'SCAN_INTERVAL', '60', 'N', '扫描NM_ALARM_EVENT表的时间间隔(秒)', 'Y', '60', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SYNC_SERVICE', 'HEARTBEAT_INTERVAL', '120', 'N', '活跃告警心跳保活间隔(秒)，应小于Alertmanager的resolve_timeout', 'N', '120', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SYNC_SERVICE', 'BATCH_SIZE', '100', 'N', '每批次处理的告警数量上限', 'N', '100', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SYNC_SERVICE', 'SYNC_ON_STARTUP', 'true', 'N', '服务启动时是否同步历史活跃告警', 'N', 'true', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SYNC_SERVICE', 'HISTORY_HOURS', '24', 'N', '历史告警回溯时长(小时)，仅在SYNC_ON_STARTUP=true时有效', 'N', '24', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SYNC_SERVICE', 'WORKER_THREADS', '4', 'N', '同步工作线程数', 'N', '4', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SYNC_SERVICE', 'ALARM_LEVELS', '1,2,3,4', 'N', '要同步的ZMC告警级别(逗号分隔): 1-严重,2-重要,3-次要,4-警告。如"1,2"表示只同步严重和重要告警', 'N', '1,2,3,4', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SYNC_SERVICE', 'SEVERITY_FILTER', '', 'N', '要同步的Prometheus severity过滤(逗号分隔): critical,error,warning,info。留空表示不过滤', 'N', '', 'SYSTEM');

-- 5.5 告警状态映射配置
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'STATUS_MAPPING', 'ZMC_STATE_U', 'FIRING', 'N', 'ZMC未确认状态(U)映射到的Prometheus状态', 'N', 'FIRING', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'STATUS_MAPPING', 'ZMC_STATE_A', 'RESOLVED', 'N', 'ZMC自动恢复状态(A)映射到的Prometheus状态', 'N', 'RESOLVED', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'STATUS_MAPPING', 'ZMC_STATE_M', 'SILENCED', 'N', 'ZMC手工清除状态(M)映射到的Prometheus状态', 'N', 'SILENCED', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SYNC_SERVICE', 'ZMC_STATE_C', 'RESOLVED', 'N', 'ZMC已确认状态(C)映射到的Prometheus状态', 'N', 'RESOLVED', 'SYSTEM');

-- 5.6 静默策略配置
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SILENCE', 'SHIELD_USE_SILENCE', 'true', 'N', 'ZMC屏蔽告警时是否使用Alertmanager Silence API', 'N', 'true', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SILENCE', 'DEFAULT_DURATION_HOURS', '24', 'N', '静默规则默认持续时长(小时)', 'N', '24', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SILENCE', 'AUTO_REMOVE_ON_CLEAR', 'true', 'N', '告警清除/恢复时是否自动删除对应的静默规则', 'N', 'true', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SILENCE', 'SILENCE_COMMENT_TEMPLATE', 'Silenced by ZMC at {time}. Operator: {operator}', 'N', '静默规则注释模板，支持{time}/{operator}等变量', 'N', 'Silenced by ZMC', 'SYSTEM');

-- 5.7 告警级别映射
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SEVERITY_MAPPING', 'ZMC_LEVEL_1', 'critical', 'N', 'ZMC告警级别1(严重)映射到的Prometheus severity', 'N', 'critical', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SEVERITY_MAPPING', 'ZMC_LEVEL_2', 'error', 'N', 'ZMC告警级别2(重要)映射到的Prometheus severity', 'N', 'error', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SEVERITY_MAPPING', 'ZMC_LEVEL_3', 'warning', 'N', 'ZMC告警级别3(次要)映射到的Prometheus severity', 'N', 'warning', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SEVERITY_MAPPING', 'ZMC_LEVEL_4', 'info', 'N', 'ZMC告警级别4(警告)映射到的Prometheus severity', 'N', 'info', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'SEVERITY_MAPPING', 'ZMC_LEVEL_0', 'warning', 'N', 'ZMC告警级别0(未定义)映射到的Prometheus severity', 'N', 'warning', 'SYSTEM');

-- 5.8 日志配置
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'LOGGING', 'LOG_LEVEL', 'INFO', 'N', '日志级别: DEBUG/INFO/WARNING/ERROR', 'N', 'INFO', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'LOGGING', 'LOG_RETENTION_DAYS', '30', 'N', 'NM_ALARM_SYNC_LOG表数据保留天数', 'N', '30', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'LOGGING', 'LOG_REQUEST_BODY', 'true', 'N', '是否记录HTTP请求体到日志表', 'N', 'true', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'LOGGING', 'LOG_RESPONSE_BODY', 'true', 'N', '是否记录HTTP响应体到日志表', 'N', 'true', 'SYSTEM');

-- 5.9 Prometheus静态标签配置
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'STATIC_LABELS', 'SOURCE', 'zmc', 'N', '静态标签: 告警来源标识', 'N', 'zmc', 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'STATIC_LABELS', 'CLUSTER', NULL, 'N', '静态标签: 集群名称', 'N', NULL, 'SYSTEM');
INSERT INTO NM_ALARM_SYNC_CONFIG (CONFIG_ID, CONFIG_GROUP, CONFIG_KEY, CONFIG_VALUE, IS_ENCRYPTED, CONFIG_DESC, IS_REQUIRED, DEFAULT_VALUE, UPDATE_BY) VALUES
(SEQ_ALARM_SYNC_CONFIG.NEXTVAL, 'STATIC_LABELS', 'DATACENTER', NULL, 'N', '静态标签: 数据中心标识', 'N', NULL, 'SYSTEM');


-- ============================================================================
-- 6. 初始化标签映射数据
-- ============================================================================
INSERT INTO NM_ALARM_LABEL_MAPPING (MAPPING_ID, SOURCE_FIELD, TARGET_LABEL, TRANSFORM_TYPE, IS_ENABLED, LABEL_TYPE, SORT_ORDER) VALUES
(SEQ_ALARM_LABEL_MAPPING.NEXTVAL, 'ALARM_NAME', 'alertname', 'DIRECT', 'Y', 'LABEL', 1);
INSERT INTO NM_ALARM_LABEL_MAPPING (MAPPING_ID, SOURCE_FIELD, TARGET_LABEL, TRANSFORM_TYPE, IS_ENABLED, LABEL_TYPE, SORT_ORDER) VALUES
(SEQ_ALARM_LABEL_MAPPING.NEXTVAL, 'HOST_IP', 'instance', 'DIRECT', 'Y', 'LABEL', 2);
INSERT INTO NM_ALARM_LABEL_MAPPING (MAPPING_ID, SOURCE_FIELD, TARGET_LABEL, TRANSFORM_TYPE, IS_ENABLED, LABEL_TYPE, SORT_ORDER) VALUES
(SEQ_ALARM_LABEL_MAPPING.NEXTVAL, 'ALARM_LEVEL', 'severity', 'LOOKUP', 'Y', 'LABEL', 3);
INSERT INTO NM_ALARM_LABEL_MAPPING (MAPPING_ID, SOURCE_FIELD, TARGET_LABEL, TRANSFORM_TYPE, IS_ENABLED, LABEL_TYPE, SORT_ORDER) VALUES
(SEQ_ALARM_LABEL_MAPPING.NEXTVAL, 'HOST_NAME', 'host', 'DIRECT', 'Y', 'LABEL', 4);
INSERT INTO NM_ALARM_LABEL_MAPPING (MAPPING_ID, SOURCE_FIELD, TARGET_LABEL, TRANSFORM_TYPE, IS_ENABLED, LABEL_TYPE, SORT_ORDER) VALUES
(SEQ_ALARM_LABEL_MAPPING.NEXTVAL, 'BUSINESS_DOMAIN', 'domain', 'DIRECT', 'Y', 'LABEL', 5);
INSERT INTO NM_ALARM_LABEL_MAPPING (MAPPING_ID, SOURCE_FIELD, TARGET_LABEL, TRANSFORM_TYPE, IS_ENABLED, LABEL_TYPE, SORT_ORDER) VALUES
(SEQ_ALARM_LABEL_MAPPING.NEXTVAL, 'APP_NAME', 'application', 'DIRECT', 'Y', 'LABEL', 6);
INSERT INTO NM_ALARM_LABEL_MAPPING (MAPPING_ID, SOURCE_FIELD, TARGET_LABEL, TRANSFORM_TYPE, IS_ENABLED, LABEL_TYPE, SORT_ORDER) VALUES
(SEQ_ALARM_LABEL_MAPPING.NEXTVAL, 'ALARM_CODE', 'alarm_code', 'DIRECT', 'Y', 'LABEL', 7);
INSERT INTO NM_ALARM_LABEL_MAPPING (MAPPING_ID, SOURCE_FIELD, TARGET_LABEL, TRANSFORM_TYPE, IS_ENABLED, LABEL_TYPE, SORT_ORDER) VALUES
(SEQ_ALARM_LABEL_MAPPING.NEXTVAL, 'EVENT_INST_ID', 'event_id', 'DIRECT', 'Y', 'LABEL', 8);
INSERT INTO NM_ALARM_LABEL_MAPPING (MAPPING_ID, SOURCE_FIELD, TARGET_LABEL, TRANSFORM_TYPE, IS_ENABLED, LABEL_TYPE, SORT_ORDER) VALUES
(SEQ_ALARM_LABEL_MAPPING.NEXTVAL, 'ENVIRONMENT', 'env', 'DIRECT', 'Y', 'LABEL', 9);
INSERT INTO NM_ALARM_LABEL_MAPPING (MAPPING_ID, SOURCE_FIELD, TARGET_LABEL, TRANSFORM_TYPE, IS_ENABLED, LABEL_TYPE, SORT_ORDER) VALUES
(SEQ_ALARM_LABEL_MAPPING.NEXTVAL, 'RES_INST_TYPE', 'resource_type', 'DIRECT', 'Y', 'LABEL', 10);

-- Annotation 映射
INSERT INTO NM_ALARM_LABEL_MAPPING (MAPPING_ID, SOURCE_FIELD, TARGET_LABEL, TRANSFORM_TYPE, IS_ENABLED, LABEL_TYPE, SORT_ORDER) VALUES
(SEQ_ALARM_LABEL_MAPPING.NEXTVAL, 'DETAIL_INFO', 'description', 'DIRECT', 'Y', 'ANNOTATION', 101);
INSERT INTO NM_ALARM_LABEL_MAPPING (MAPPING_ID, SOURCE_FIELD, TARGET_LABEL, TRANSFORM_TYPE, IS_ENABLED, LABEL_TYPE, SORT_ORDER) VALUES
(SEQ_ALARM_LABEL_MAPPING.NEXTVAL, 'ALARM_NAME', 'summary', 'DIRECT', 'Y', 'ANNOTATION', 102);
INSERT INTO NM_ALARM_LABEL_MAPPING (MAPPING_ID, SOURCE_FIELD, TARGET_LABEL, TRANSFORM_TYPE, IS_ENABLED, LABEL_TYPE, SORT_ORDER) VALUES
(SEQ_ALARM_LABEL_MAPPING.NEXTVAL, 'FAULT_REASON', 'fault_reason', 'DIRECT', 'Y', 'ANNOTATION', 103);
INSERT INTO NM_ALARM_LABEL_MAPPING (MAPPING_ID, SOURCE_FIELD, TARGET_LABEL, TRANSFORM_TYPE, IS_ENABLED, LABEL_TYPE, SORT_ORDER) VALUES
(SEQ_ALARM_LABEL_MAPPING.NEXTVAL, 'DEAL_SUGGEST', 'runbook', 'DIRECT', 'Y', 'ANNOTATION', 104);


-- ============================================================================
-- 7. 日志清理存储过程
-- ============================================================================
CREATE OR REPLACE PROCEDURE SP_CLEAN_ALARM_SYNC_LOGS AS
    v_retention_days NUMBER;
    v_deleted_count  NUMBER;
BEGIN
    -- 获取日志保留天数配置
    SELECT NVL(CONFIG_VALUE, DEFAULT_VALUE) INTO v_retention_days
    FROM NM_ALARM_SYNC_CONFIG
    WHERE CONFIG_GROUP = 'LOGGING' AND CONFIG_KEY = 'LOG_RETENTION_DAYS';

    -- 删除过期日志
    DELETE FROM NM_ALARM_SYNC_LOG
    WHERE CREATE_TIME < SYSTIMESTAMP - NUMTODSINTERVAL(v_retention_days, 'DAY');

    v_deleted_count := SQL%ROWCOUNT;

    -- 记录清理操作
    INSERT INTO NM_ALARM_SYNC_LOG (LOG_ID, OPERATION, REQUEST_PAYLOAD, CREATE_TIME)
    VALUES (SEQ_ALARM_SYNC_LOG.NEXTVAL, 'LOG_CLEANUP',
            '{"retention_days": ' || v_retention_days || ', "deleted_count": ' || v_deleted_count || '}',
            SYSTIMESTAMP);

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END SP_CLEAN_ALARM_SYNC_LOGS;
/

COMMENT ON PROCEDURE SP_CLEAN_ALARM_SYNC_LOGS IS '清理过期的同步日志记录，根据LOGGING.LOG_RETENTION_DAYS配置执行';


-- ============================================================================
-- 8. 配置查询视图
-- ============================================================================
CREATE OR REPLACE VIEW V_ALARM_SYNC_CONFIG AS
SELECT
    CONFIG_GROUP,
    CONFIG_KEY,
    CASE
        WHEN IS_ENCRYPTED = 'Y' THEN '******'
        ELSE NVL(CONFIG_VALUE, DEFAULT_VALUE)
    END AS EFFECTIVE_VALUE,
    CONFIG_DESC,
    IS_REQUIRED,
    IS_ENCRYPTED,
    UPDATE_TIME
FROM NM_ALARM_SYNC_CONFIG
ORDER BY CONFIG_GROUP, CONFIG_KEY;

COMMENT ON TABLE V_ALARM_SYNC_CONFIG IS '配置查询视图，隐藏加密字段的实际值，仅显示******';


-- ============================================================================
-- 9. 同步状态统计视图
-- ============================================================================
CREATE OR REPLACE VIEW V_ALARM_SYNC_STATISTICS AS
SELECT
    SYNC_STATUS,
    COUNT(*) AS ALARM_COUNT,
    MIN(CREATE_TIME) AS EARLIEST_ALARM,
    MAX(UPDATE_TIME) AS LATEST_UPDATE,
    SUM(PUSH_COUNT) AS TOTAL_PUSHES,
    SUM(ERROR_COUNT) AS TOTAL_ERRORS
FROM NM_ALARM_SYNC_STATUS
GROUP BY SYNC_STATUS;

COMMENT ON TABLE V_ALARM_SYNC_STATISTICS IS '同步状态统计视图，按状态分组统计告警数量和推送情况';


COMMIT;
